### ISSUE TITLE
NG cockpit is used to manage customers & organizations entities

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/junior_hybris_mentoring_alex#12]
As a **content manager**
I want to be able to change customers and organizations attributes in more modern way
So that backoffice extension is added to B2C accelerator

**AC:**
1. Organizations node is added to backoffice objects tree
2. Organizations manager is able to perform CRUD-operations with organizations & customers via backoffice web-page.

*Tips:*
https://wiki.hybris.com/display/release5/Include+-+Create+a+Custom+Backoffice+Extension 
https://wiki.hybris.com/display/tr52/Trail+~+Customizing+Backoffice+-+Cockpit+NG

**Comment by cr0wfoot** [comment]
done

![backoffice_customer](https://cloud.githubusercontent.com/assets/12846266/14427246/7d3efdf8-fffc-11e5-8704-ef95489d2566.jpg)
![backoffice_organization](https://cloud.githubusercontent.com/assets/12846266/14427247/803e19f8-fffc-11e5-9368-86b0079e8844.jpg)
