### ISSUE TITLE
Let organization customers receive e-mails

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/junior_hybris_mentoring_alex#13]
As an **organization manager**
I want to be on the same page with organization contents
So that I receive daily email with list of users in my organization

**AC**
Email is sent to each organization manager whose address is set as an Organization.email attribute.
The email should contain list of all users in this organization. 
E-mail should be constructed via .vm template and should look fine. E-mail termplate should be imported using standard impex approach.

**Mail server configuration**
mail.from=darwinepam@gmail.com
mail.replyto=darwinepam@gmail.com
mail.smtp.server=smtp.gmail.com
mail.smtp.port=587
mail.smtp.user=darwinepam@gmail.com
mail.smtp.password=DarwinDarwin
mail.smtp.starttls.enable=true
mail.use.tls=true

**Comment by cr0wfoot** [comment]
works correctly

![send_mail](https://cloud.githubusercontent.com/assets/12846266/14427816/1cb0022c-ffff-11e5-8aa1-89ec58498f20.jpg)

**Comment by cr0wfoot** [comment]
vm 
![vm](https://cloud.githubusercontent.com/assets/12846266/14608154/2d3141d6-058d-11e6-80d7-3f399108781c.jpg)

**Comment by cr0wfoot** [comment]
![sendmailjob](https://cloud.githubusercontent.com/assets/12846266/14637659/6e05949c-063b-11e6-84d1-a7f00dee5772.jpg)
