### ISSUE TITLE
Generate an error message when organization name length is greater than 15 simbols

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/junior_hybris_mentoring_alex#16]
As a **content manager**
I want to have a constraint for organization's name attribute
So that an appropriate constraint is created via ImpEx and is available in Admin cockpit.

**AC**
Aftert an attempt to set a long value for organization name an appropriate contraint generated an error
Constraint is created using ImpEx and could be changed in Admin cockpit

*Tips:*
https://wiki.hybris.com/display/R5T/Trail+~+Validation

**Comment by cr0wfoot** [comment]
done
![organizationconstraints](https://cloud.githubusercontent.com/assets/12846266/14676177/032406c4-0715-11e6-9a1f-139b40784ad4.jpg)
