### ISSUE TITLE
Change default HAC URL to be “/hac”

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/junior_hybris_mentoring_alex#18]
As **hybris admin** 
I want to have more flexible way to access hAC
So that to perform an access to hybris Admin Console I use "http://{host:port}/hac" URL

**AC**
Access to hAC is performer after sending a request to "http://{host:port}/hac" URL

*Tips*
local.properties file
hac.webroot && hmc.webroot properties there

**Comment by cr0wfoot** [comment]
used
https://wiki.hybris.com/display/release5/Setting+the+Web+Application+of+an+Extension


![hac](https://cloud.githubusercontent.com/assets/12846266/14742877/171112ce-08a7-11e6-8c1c-a5efa6cdcfda.jpg)
