### ISSUE TITLE
Develop an AddOn which allows to add random / theme images carousel via WCMS module

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/junior_hybris_mentoring_alex#23]
As a *content manager*
I want to have a possibility to add random / theme images carousels to pages using CMS module means
So that an AddOn is developed which provides us this functionality

*Technical tips:*
https://wiki.hybris.com/display/R5T/Creating+New+CMS+Components

**Comment by cr0wfoot** [comment]
![addon](https://cloud.githubusercontent.com/assets/12846266/15217807/e0c14fb2-1865-11e6-9814-a11fe736728c.jpg)
